dss/app_news/urls.py
from django.urls import path
from .views import NewsListView, NewsDetailView

app_name = 'news'
urlpatterns = [
    path('', NewsListView.as_view(), name='list'),
    path('<slug:slug>/', NewsDetailView.as_view(), name='detail'),
]

dss/app_search/urls.py
from . import views
from django.urls import path

app_name = 'search'
urlpatterns = [
    path('', views.result, name='result_list'),
    
]

dss/app_services/urls.py
from django.contrib import admin
from django.urls import path
from .views import DetailServiceView, ListServiceView, ListTypeServiceView, campingview, sectionview

app_name = 'app_services'

urlpatterns = [
    # path('', ListServiceView.as_view(), name='all'),
    path('camping/', campingview, name='camping'),
    path('hardsection/<slug:section>/', sectionview, name='hardsection'),
    path('<slug:category>/', ListTypeServiceView.as_view(), name='categoryservice'),
    path('<slug:category>/<slug:typesrvc>', ListServiceView.as_view(), name='listservice'),
    path('detail/<slug:slug>/', DetailServiceView.as_view(), name='detail'),
    
    
]

dss/dss/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('home.urls', namespace='home')),
    path('lk/', include('app_lk.urls', namespace='lk')),
    path('objects/', include('app_objects.urls', namespace='objects')),
    path('services/', include('app_services.urls', namespace='services')),
    path('about/', include('app_about.urls', namespace='about')),
    path('user/', include('app_user.urls', namespace='user')),
    path('mediafiles/', include('app_mediafiles.urls', namespace='app_mediafiles')),
    path('news/', include('app_news.urls', namespace='news')),
    path('search', include('app_search.urls', namespace='search')),
]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dss/home/urls.py
from django.urls import path
from .views import IndexView

app_name = 'home'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    
]

dss/home/views.py
from django.views.generic.base import TemplateView
from common.mixins import TitleMixin, ObjectsMixin
from app_objects.models import Object
from app_services.models import TypeService


class IndexView(TitleMixin, ObjectsMixin, TemplateView):
    template_name = 'home/index_dep.html'
    title = "главная"
    objects = Object.objects.all().order_by('-order')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['sportservices'] = TypeService.objects\
            .filter(category='sport')\
            .filter(active=True)\
            .order_by('-order')
        context['relaxservices'] = TypeService.objects.filter(category='relax').order_by('-order')
        return context
    

dss/home/templates/home/base2lv.html
{% load static %}
{% extends 'home/base_dep.html' %}

{% block css %}
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
          <div class="col">
            {% block bradcrumbs %}
            {% endblock%}
          </div>
          <div class="col d-none d-md-block">
            <form action="{% url 'search:result_list' %}" method='get'>
              <div class="form-row">
                <div class="col-9">
                  <input class="form-control" type="search" name="search" type="text" placeholder="поиск..." aria-label="Search">
                </div>
                <div class="col">
                  <button class="form-control btn btn-outline-primary" type="submit">Найти</button>
                </div>
              </div>
            </form>
          </div>
          
        </div>
      </div>
    
    <div class="container-fluid">
        <div class="row">
          {% block promo_slider %}
          {% endblock %}
        </div>
    </div>
        <hr>
    <div class="container-fluid">
        <div class="row">
            <div class="col">
            {% block content %}
            {% endblock %}
            </div>
        </div>
    </div>
{% endblock %}
    {% comment %} <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    <script src="{% static 'home/js/deploymain.js' %}"></script> {% endcomment %}

dss/home/templates/home/base2lv_ext.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    {% block seo %}
    {% endblock %}
    <link rel="shortcut icon" type="image/png" href="{% static 'home/favicon.ico' %}"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'home/css/stylenew.css'%}"/>
    <link rel="stylesheet" href="{% static 'home/css/header.css'%}"/>
    
    {% block css %}
    {% endblock %}
</head>
<body>
    {% include 'home/header_dep.html' %}
    <div class="container-fluid">
        <div class="row">
          <div class="col">
            {% block bradcrumbs %}
            {% endblock%}
          </div>
          <div class="col d-none d-md-block">
            <form action="{% url 'search:result_list' %}" method='get'>
              <div class="form-row">
                <div class="col-9">
                  <input class="form-control" type="search" name="search" type="text" placeholder="поиск..." aria-label="Search">
                </div>
                <div class="col">
                  <button class="form-control btn btn-outline-primary" type="submit">Найти</button>
                </div>
              </div>
            </form>
          </div>
          
        </div>
      </div>
    
    <div class="container-fluid">
        <div class="row">
          {% block promo_slider %}
          {% endblock %}
        </div>
    </div>
        <hr>
    <div class="container-fluid">
        <div class="row">
            <div class="col">
            {% block content %}
            {% endblock %}
            </div>
        </div>
    </div>
    {% include 'home/footer_dep.html' %}
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    <script src="{% static 'home/js/deploymain.js' %}"></script>
</body>
</html>

dss/home/templates/home/base3lv_ext.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ДСС: {{ title }}</title>
    {% block seo %}
    {% endblock %}
    <link rel="shortcut icon" type="image/png" href="{% static 'home/favicon.ico' %}"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'home/css/stylenew.css'%}"/>
    <link rel="stylesheet" href="{% static 'home/css/header.css'%}"/>
    {% block css %}
    {% endblock %}
    <script>
      $(function () {
        $('[data-toggle="tooltip"]').tooltip()
      })
    </script>
</head>

</head>
<body>
  {% include 'home/header_dep.html' %}
  <div class="container-fluid">
    <div class="row">
      <div class="col">
        {% block bradcrumbs %}
        {% endblock%}
      </div>
      <div class="nav col">
        <div class="nav-item">
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="_" aria-label="Search">
            <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Найти</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <div class="container-fluid">
    <div class="row">
      <div class="col">
        {% block promo_slider %}
        {% endblock %}
      </div>
    </div>
  </div>
  <hr>
  <div class="container-fluid">
      <div class="row">
        <div class="col">
          {% block content %}
          {% endblock %}
        </div>
      </div>
  </div>
  {% include 'home/footer_dep.html' %}
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    <script src="{% static 'home/js/deploymain.js' %}"></script>
    <script>
      $("input[type=checkbox][name=object]").on("click", function () {
        const arrayChecked = []
        $("input[name*='object']:checked").each(function() {
          arrayChecked.push($(this).val());
        });
        let url = $(location).attr('href');
        let form = document.createElement('form');
        form.action = url;
        form.method = 'GET';
        let value = arrayChecked.join()
        form.innerHTML = `<input name="objects" value="${value}">`;
        document.body.append(form);
        form.submit();
    })
    </script>
</body>
</html>

dss/home/templates/home/base_dep.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@10/swiper-bundle.min.css"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700;900&display=swap" rel="stylesheet">
    <link rel="icon" type="image/x-icon" href="{% static 'home/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'home/css/reset.css'%}">
    <link rel="stylesheet" href="{% static 'home/css/header.css'%}">
    <link rel="stylesheet" href="{% static 'home/css/footer.css'%}"/>
    {% block style %}
    {% endblock %}
    <title>ДСС: {{title}}</title>
</head>
<body class="background">
    {% include 'home/header_dep.html' %}

    {% block content %}
    {% endblock %}

    {% include 'home/footer_dep.html' %}

    {% comment %} <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script> {% endcomment %}
    
    <script src="https://cdn.jsdelivr.net/npm/swiper@10/swiper-bundle.min.js"></script>
    <script src="{% static 'home/js/deploymain.js' %}"></script>
</body>
</html>

dss/home/templates/home/base_lk.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@10/swiper-bundle.min.css"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'home/css/indexstyle.css'%}">
    <link rel="stylesheet" href="{% static 'home/css/stylenew.css'%}"/>
    <title>ДСС: личный кабинет</title>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.7.0/dist/jquery.min.js"></script>
    <!-- Start 1C Fitness JS Code Insert after jQuery. DO NOT CHANGE! -->
    <script src="https://reservi.ru/widget-fit1c.v2/js/config.js" data-fit-salon-id="472b94d9-2266-457c-a867-fc2739150423"></script>
    
</head>
<body>
    {% include 'home/header_dep.html' %}

    {% block content %}
    {% endblock %}

    {% include 'home/footer_dep.html' %}
    <script src="https://cdn.jsdelivr.net/npm/swiper@10/swiper-bundle.min.js"></script>
    <script src="{% static 'home/js/deploymain.js' %}"></script>   
</body>
</html>

dss/home/templates/home/footer_dep.html
{% load static %}

<footer class="footer">
    <div class="wrapper footer-wrapper">
        <img src="{% static 'home/image/footer-back.svg' %}" alt="back" class="footer-back">
        <p class="footer-text">© ГАУ РБ "ДИРЕКЦИЯ СПОРТИВНЫХ СООРУЖЕНИЙ</p>
        <div class="footer-link">
            <img src="{% static 'home/image/image12.png' %}" alt="link">
        </div>
    </div>
</footer>

dss/home/templates/home/header_dep.html
{% load static %}
<header class="header">
    <div class="wrapper">
        <ul class="menu-none">
            <img src="{% static 'home/image/burger_menu-close.svg' %}" alt="кнопка закрыть" class="close-btn">
            <h6 class="menu-title">Меню</h6>
            {% load menubuilder %}
            {% menu mainmenu %}
            {% for item in menuitems %}
            <li class="menu__list-item">
                <a href="{{ item.url }}" title="{{ item.title|escape }}">
                    {{ item.title }}
                </a>
            </li>
            {% endfor %}
            
        </ul>
        <div class="header-top">
            <div class="call-center">
                <p class="call-center__title">Call-центр</p>
                <div class="call-center__phone">+7 (3012) 45-30-36</div>
            </div>
            <div class="header-top__left">
                <a href="{% url 'news:list'%}" class="header-top__left-registr">
                    <img src="{% static 'home/image/news.svg'%}" alt="иконка новости">
                    <span>Новости</span>
                </a>
                <a href="#" class="header-top__left-registr">
                    <img src="{% static 'home/image/man.svg' %}" alt="иконка человек">
                    <span>Личный кабинет</span>
                </a>
            </div>
        </div>
        <div class="header__content">
            <a href="{% url 'home:index' %}" class="logo">
                <img src="{% static 'home/image/logo.png' %}" alt="логотип ДСС">
            </a>
            <menu class="header__menu">
                <ul class="header__menu-list">
                    {% load menubuilder %}
                    {% menu mainmenu %}
                    {% for item in menuitems %}
                    <li class="menu__list-item">
                        <a href="{{ item.url }}" title="{{ item.title|escape }}">
                            {{ item.title }}
                        </a>
                    </li>
                    {% endfor %}
                </ul>
                <div class="burger">
                    <div></div>
                </div>
            </menu>
        </div>
    </div>
</header>

dss/home/templates/home/index_dep.html
{% extends 'home/base_dep.html' %}

{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'home/css/body-screen.css' %}">
<link rel="stylesheet" href="{% static 'home/css/main-index.css' %}">
{% endblock %}

{% block content %}
<main class="main">
    <section class="cards">
        <div class="wrapper wrapper-card">
            <img src="{% static 'home/image/back.png' %}" alt="back" class="background-block">
            <div class="swiper mySwiper">
                <div class="swiper-wrapper">
                  <div class="swiper-slide">
                    <div class="card">
                        <div class="content">
                          <div class="front front-one">
                            <h2 class="front-title">Наши объекты</h2>
                          </div>
                          <div class="back back-one">
                            <h2 class="front-title">Наши объекты</h2>
                            <ul>
                            {% for object in objects %}
                                <li>
                                    <a href="{% url 'objects:detail' object.slug %}">
                                        {{ object.short_name|upper }}
                                    </a>
                                </li>
                            {% endfor %}
                            </ul>
                          </div>
                        </div>
                    </div>
                  </div>
                  <div class="swiper-slide">
                    <div class="card">
                        <div class="content">
                          <div class="front front-two">
                            <h2 class="front-title">Спорт</h2>
                          </div>
                          <div class="back back-one">
                            <h2 class="back-title">Спорт</h2>
                            <ul>
                                {% for sportservice in sportservices %}
                                <li>
                                    <a href="{% url 'services:listservice' 'sport' sportservice.slug %}">
                                        {{sportservice.name|upper}}
                                    </a>
                                </li>
                                {% endfor %}
                            </ul>
                          </div>
                        </div>
                    </div>
                  </div>
                  <div class="swiper-slide">
                    <div class="card">
                        <div class="content">
                          <div class="front front-three">
                            <h2 class="front-title">Отдых</h2>
                          </div>
                          <div class="back back-one">
                            <h2 class="front-title">Отдых</h2>
                            <ul>
                            {% for relaxservice in relaxservices %}
                                <li>
                                    <a href="{% url 'services:listservice' 'relax' relaxservice.slug %}">
                                        {{relaxservice.name|upper}}
                                    </a>
                                </li>
                            {% endfor %}
                            </ul>
                          </div>
                        </div>
                    </div>
                  </div>
                </div>
              </div>
            <!-- <div class="container-card">
                <div class="cards-wrap">

                </div>
            </div> -->
        </div>
    </section>
</main>
{% endblock %}

dss/home/templates/home/promo.html
<div class="container-fluid">
    <div class="row">
        
        <div class="col-9">
            <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                  <div class="carousel-item active">
                    <img class="d-block w-100" src="..." alt="Первый слайд">
                  </div>
                  <div class="carousel-item">
                    <img class="d-block w-100" src="..." alt="Второй слайд">
                  </div>
                  <div class="carousel-item">
                    <img class="d-block w-100" src="..." alt="Третий слайд">
                  </div>
                </div>
              </div>
            </div>
    </div>
</div>

dss/home/templates/home/promowithbc.html
<div class="container-fluid">
    <div class="row">
      {{object}}
        <div class="col">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb" itemscope itemtype="https://schema.org/BreadcrumbList">
                  <li class="breadcrumb-item" itemprop='itemListElement' itemscope itemtype='https://schema.org/ListItem'>
                    <a href="{% url 'home:index' %}" itemprop="item">
                      <span itemprop="name">Главная</span>
                    </a>
                  </li>
                  <li class="breadcrumb-item" itemprop='itemListElement' itemscope itemtype='https://schema.org/ListItem'>
                    <a href="{% url 'objects:index' %}" itemprop="item">
                      <span itemprop="name">Объекты</span>
                    </a>
                  </li>
                  <li class="breadcrumb-item active" aria-current="page">
                    <a href="#" itemprop="item"> 
                      <span itemprop="name">{{object.short_name}}</span>
                    </a>
                  </li>
                </ol>
              </nav>
        </div>
        <div class="col-9">
            <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                  <div class="carousel-item active">
                    <img class="d-block w-100" src="..." alt="Первый слайд1">
                  </div>
                  <div class="carousel-item">
                    <img class="d-block w-100" src="..." alt="Второй слайд">
                  </div>
                  <div class="carousel-item">
                    <img class="d-block w-100" src="..." alt="Третий слайд">
                  </div>
                </div>
              </div>
            </div>
    </div>
</div>