dss/app_user/urls.py
from django.contrib import admin
from django.urls import path
from .views import AuthView, MyLogoutView, RegisterUserView, ProfileEditView, VerificationView



app_name = 'user'

urlpatterns = [
    # path('logout', products, name='index'),
    path('login', AuthView.as_view(), name='login'),
    path('register', RegisterUserView.as_view(), name='register'),
    path('profile/<int:pk>', ProfileEditView.as_view(), name='profile'),
    path('logout', MyLogoutView.as_view(), name='logout'),
    path('verificated/<str:email>/<uuid:code>', VerificationView.as_view(), name='verificated'),
]

dss/dss/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('home.urls', namespace='home')),
    path('lk/', include('app_lk.urls', namespace='lk')),
    path('objects/', include('app_objects.urls', namespace='objects')),
    path('services/', include('app_services.urls', namespace='services')),
    path('about/', include('app_about.urls', namespace='about')),
    path('user/', include('app_user.urls', namespace='user')),
    path('mediafiles/', include('app_mediafiles.urls', namespace='app_mediafiles')),
    path('news/', include('app_news.urls', namespace='news')),
    path('search', include('app_search.urls', namespace='search')),
]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dss/app_user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    image = models.ImageField(
        verbose_name='аватар',
        upload_to='users',
        null=True,
        blank=True)
    is_verified_email = models.BooleanField(
        verbose_name='верефикация email',
        default=False)


class VerifideUser(models.Model):
    code = models.UUIDField(
        verbose_name='uuid',
        unique=True)
    user = models.ForeignKey(User,
                             verbose_name='пользователь',
                             on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True,
                                   verbose_name='время создания')
    expiration = models.DateTimeField(verbose_name='действует до')

    def __str__(self):
        return f"{self.user.email} - {self.code}"

dss/app_user/forms.py
from django.contrib.auth.forms import AuthenticationForm, \
                                        UserCreationForm, \
                                        UserChangeForm
from .models import User, VerifideUser
from django import forms
from django.utils.timezone import now
from datetime import timedelta
from django.conf import settings
from uuid import uuid4
from django.core.mail import send_mail
from django.urls import reverse

class FormAuth(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control py-4',
            'placeholder': 'Введите имя пользователя'
        }
    ))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
        'class': 'form-control py-4',
        'placeholder': 'Введите пароль'
        }
    ))
    class Meta:
        model = User
        fields = ('username', 'password')


class FormRegister(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control py-4',
            'placeholder': 'Введите имя'
        }
    ))
    last_name = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control py-4',
            'placeholder': 'Введите фамилию'
        }
    ))
    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control py-4',
            'placeholder': 'Введите имя пользователя',
            'aria-describedby': "usernameHelp"
        }
    ))
    email = forms.CharField(widget=forms.EmailInput(
        attrs={
            'class': 'form-control py-4',
            'placeholder': 'Введите адрес эл. почты',
            'aria-describedby': "emailHelp",
        }
    ))
    password1 = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control py-4',
            'placeholder': 'Введите пароль'
        }
    ))
    password2 = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control py-4',
            'placeholder': 'Подтвердите пароль'
        }
    ))

    class Meta:
        model = User
        fields = ('first_name', 'last_name',
                  'username', 'email', 'password1', 'password2')

    def save(self, commit: bool = True):
        user = super().save(commit)
        expiration = now() + timedelta(hours=settings.EXPIRATION_VERIFIED)
        record = VerifideUser.objects.create(user=user,
                                             code=uuid4(),
                                             expiration=expiration)
        path = reverse('user:verificated', kwargs={
            'email': user.email,
            'code': record.code})
        link = f"{settings.DOMAIN_LINK}{path}"
        message = f"""
        Вы успешно зарегистрировались на сайте с логином {user.username}.
        Для верификации электронной почты {user.email} перейдите по ссылке:
        {link}
        Ссылка действует до {str(record.expiration)}"""
        send_mail(
            'Верификация email на сайте Магазин Store',
            message,
            settings.EMAIL_FROM,
            [user.email],
            fail_silently=False)
        return user

class FormChangeProfile(UserChangeForm):
    first_name = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control py-4',
            
        }
    ))
    last_name = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control py-4',
            
        }
    ))
    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control py-4',
            'readonly': True,
            'aria-describedby': "usernameHelp"
        }
    ))
    email = forms.CharField(widget=forms.EmailInput(
        attrs={
            'class': 'form-control py-4',
            'readonly': True,
            'aria-describedby': "emailHelp"
        }),
        required=False)
    image = forms.ImageField(widget=forms.FileInput(
        attrs= {
            'class': 'custom-file-input',
            'size': '50',
        }),
        required=False)
    
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'image')
        

dss/app_user/views.py
# from catalog.models import Basket
# from django.contrib import auth, messages
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.messages.views import SuccessMessageMixin
# from django.shortcuts import HttpResponseRedirect, render
from django.urls import reverse_lazy, reverse

from django.views.generic import TemplateView
from django.views.generic.edit import CreateView, UpdateView
from django.shortcuts import get_object_or_404, HttpResponseRedirect

from .forms import FormAuth, FormChangeProfile, FormRegister
from .models import User, VerifideUser
from common.mixins import TitleMixin

from django.utils.timezone import now


class AuthView(TitleMixin, LoginView):
    template_name = 'user/login.html'
    authentication_form = FormAuth
    next_page = '/'
    title = "ДСС: Аутентификация"


class RegisterUserView(SuccessMessageMixin, TitleMixin, CreateView):
    model = User
    template_name = 'user/register.html'
    form_class = FormRegister
    success_url = '/user/login'
    success_message = 'успешно зарегестрирован'
    title = "ДСС: Регистрация"


class ProfileEditView(TitleMixin, UpdateView):
    model = User
    form_class = FormChangeProfile
    template_name = 'user/profile.html'
    success_message = 'профиль изменен'
    title = "ДСС: Профиль"

    def get_success_url(self) -> str:
        return reverse_lazy('user:profile', kwargs={'pk': self.object.id})


class MyLogoutView(LogoutView):
    pass


class VerificationView(TitleMixin, TemplateView):
    template_name = 'user/email_verification.html'
    title = 'ДСС: верефицирован'

    # TODO send message error on index page
    def get(self, request, *args, **kwargs):
        email = kwargs.get('email', '')
        uuid_str = kwargs.get('code', '')
        # try:
        #     code = uuid.UUID(uuid_str)
        # except ValueError:
        #     # return HttpResponseNotFound('uuid is not valide')
        #     return HttpResponseRedirect(reverse('index'))
        # ставь в urls uuid и проверять не придется, не найдет на этапе маршрутизации
        users = User.objects.filter(email=email)
        if users.exists():
            user = users.last()
        record = VerifideUser.objects.filter(user=user, code=uuid_str).last()
        if record:
            if record.expiration > now():
                user.is_verified_email = True
                user.save()
                # record.delete()
                return super().get(request, *args, **kwargs)
            else:
                print('time out')
        else:
            print('uuid not found')
        return HttpResponseRedirect(reverse('index'))

dss/app_user/templates/user/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{{ title }}</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'home/favicon.ico' %}"/>
    <link href={% static "app_user/css/auth.css" %} rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="bg-primary">
 {% block content %}
 {% endblock %}
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src={% static "app_user/js/auth-admin.js" %}></script>
</body>
</html>

dss/app_user/templates/user/basket.html
<div class="col-lg-5">
    <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
        Корзина <span class="badge badge-secondary badge-pill">{{ basket.total_quantity }}</span>
    </h4>
    {% for inbasket in basket %}
    <div class="card mb-3">
        <div class="card-body">
            <h5 class="card-title">{{ inbasket.product.name }}</h5>
            <p class="card-text mb-0">{{ inbasket.product.short_description}}</p>
            <p class="card-text mt-0">цена: {{ inbasket.product.price}}</p>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item bg-light">
                <div class="row text-center">
                    <div class="col-lg-4">
                        <input name="basketID" type="number" class="form-control"
                               value="{{ inbasket.quantity }}" min="0">
                    </div>
                    <div class="col-lg-4">{{ inbasket.sum }}</div>
                    <div class="col-lg-4">
                        <a href={% url 'product:remove_product_from_basket' inbasket.product.id %}>
                            <i class="fas fa-trash"></i>
                        </a>
                    </div>
                </div>
            </li>
        </ul>
    </div>
    {% empty %}
    <div class="card mb-3">
        <p>Корзина пуста</p>
    </div>
    {% endfor %}
    <div class="card mb-3">
        <div class="card-footer">
            <p class="float-left">Итого</p>
            <h4 class="float-right">{{ basket.total_sum }}</h4>
        </div>
    </div>
    <a class="btn btn-success btn-lg float-right 
    {% if not basket %} disabled {% endif %}" 
    href="../orders/order-create.html">
    
        Оформить заказ
    </a>
</div>

dss/app_user/templates/user/email_verification.html
{% extends 'user/base.html' %}

{% block content %}
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-5">
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header"><h3 class="text-center font-weight-light my-4">Поздравляем</h3>
                            </div>
                            <div class="card-body text-center">
                                <h4>Ваша учетная запись успешно подтверждена!</h4>
                            </div>
                            <div class="card-footer text-center">
                                <div class="small"><a href={% url 'index' %}>Продолжить</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
{% endblock %}

dss/app_user/templates/user/login.html
{% extends 'user/base.html' %}

{% load static %}

{% block content %}
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-5">
                        {% if messages or form.non_field_errors %}
                        {% for message in messages %}
                        <div class="alert alert-success alert-dismissible fade show" role="alert"
                             style="margin-top: 50px;">
                            {{ message }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        {% endfor %}
                        {% if form.non_field_errors %}
                        <div class="alert alert-warning alert-dismissible fade show" role="alert"
                             style="margin-top: 50px;">
                            {{ form.non_field_errors }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        {% endif %}
                        {% endif %}
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header"><h3 class="text-center font-weight-light my-4">Авторизация</h3>
                            </div>
                            <div class="card-body">
                                <form method="post" action={% url 'user:login' %}>
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <label class="small mb-1" for={{ form.username.id_for_label }}>Имя пользователя</label>
                                        {{ form.username }}
                                    </div>
                                    <div class="form-group">
                                        <label class="small mb-1" for={{ form.password.id_for_label }}>Пароль</label>
                                        {{ form.password }}
                                    </div>
                                    <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                        <a class="small" href="#">Забыли пароль?</a>
                                        <input class="btn btn-primary" type="submit" value="Авторизоваться">
                                    </div>
                                    <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                        <a href="#">
                                            <i class="fab fa-google fa-2x" style="color: #d9503e;"></i>
                                        </a>
                                        <a href="#">
                                            <i class="fab fa-vk fa-2x" style="color: #4a658b;"></i>
                                        </a>
                                        <a href="#">
                                            <i class="fab fa-github fa-2x" style="color: #303030;"></i>
                                        </a>
                                        <a href="#">
                                            <i class="fab fa-facebook fa-2x" style="color: #405794;"></i>
                                        </a>
                                    </div>
                                </form>
                            </div>
                            <div class="card-footer text-center">
                                <div class="small"><a href={% url "user:register" %}>Нужен аккаунт? Зарегистрируйся!</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>
{% endblock %}

dss/app_user/templates/user/profile.html
{% extends 'catalog/base.html' %}
{% load static %}
{% block css %}
     <!-- Custom styles for this template -->
    <link href={% static "vendor/css/profile.css" %} rel="stylesheet">
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-7">
            <h4 class="mt-3 mb-3">Профиль</h4>
            <div class="col-lg-12 text-center">
                <img width="100" height="100"
                     src={% if user.image %} {{ user.image.url }} {% else %} {% static 'vendor/img/default_avatar.jpg' %} {% endif %}
                     class="img-thumbnail">
            </div>
            <form action={% url "user:profile" user.id %} method="post" enctype="multipart/form-data">
                {% csrf_token %}
                
                <div class="form-row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for={{ form.first_name.id_for_label }}>Имя</label>
                            {{ form.first_name }}
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for={{ form.last_name.id_for_label }}>Фамилия</label>
                            {{ form.last_name }}
                        </div>
                    </div>
                </div>
                <div class="form-row mb-2">
                    <div class="col-lg-12">
                        <div class="custom-file">
                            {{ form.image }}
                            <label class="custom-file-label" for={{ form.image.id_for_label }}>Выберите изображение</label>
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-6">
                        <label class="small mb-1" for={{ form.username.id_for_label }}>Имя пользователя</label>
                        {{ form.username }}
                    </div>
                    <div class="col-lg-6">
                        <label class="small mb-1" for={{ form.email.id_for_label }}>Адрес электронной
                            почты</label>
                        {{ form.email }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                    </div>
                </div> 
            </form>
        </div>
        {% include 'user/basket.html' %}
    </div>
</div>
{% endblock %}

dss/app_user/templates/user/register.html
{% extends 'user/base.html' %}

{% load static %}

{% block content %}
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-7">
                        {% if form.errors %}
                        <div class="alert alert-warning alert-dismissible fade show" role="alert"
                             style="margin-top: 50px;">
                             {{ form.errors }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        {% endif %}
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header"><h3 class="text-center font-weight-light my-4">Создать аккаунт</h3>
                            </div>
                            <div class="card-body">
                                <form method="post" active={% url 'user:register' %}>
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for={{ form.first_name.id_for_label }}>Имя</label>
                                                {{ form.first_name }}
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for={{ form.last_name.id_for_label }}>Фамилия</label>
                                                {{ form.last_name }}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            <label class="small mb-1" for={{ form.username.id_for_label }}>Имя пользователя</label>
                                            {{ form.username }}
                                        </div>
                                        <div class="col-md-6">
                                            <label class="small mb-1" for={{ form.username.id_for_label }}>Адрес электронной
                                                почты</label>
                                            {{ form.email }}
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for={{ form.password1.id_for_label }}>Пароль</label>
                                                {{ form.password1 }}
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for={{ form.password2.id_for_label }}>Подтверждение
                                                    пароля</label>
                                                {{ form.password2 }}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group mt-4 mb-0">
                                        <input class="btn btn-primary btn-block" type="submit" value="Создать аккаунт">
                                    </div>
                                </form>
                            </div>
                            <div class="card-footer text-center">
                                <div class="small"><a href={% url "user:login" %}>Уже есть аккаунт? Авторизоваться</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>
{% endblock %}