dss/app_objects/urls.py
from django.contrib import admin
from django.urls import path
from .views import IndexView, DetailObjectView, ListObjectsView, DetailAreaView

app_name = 'app_objects'

urlpatterns = [
    path('', ListObjectsView.as_view(), name='index'),
    path('<str:slug>', DetailObjectView.as_view(), name='detail'),
    path('<str:obj_slug>/<str:slug>/', DetailAreaView.as_view(), name='area')
]

dss/dss/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('home.urls', namespace='home')),
    path('lk/', include('app_lk.urls', namespace='lk')),
    path('objects/', include('app_objects.urls', namespace='objects')),
    path('services/', include('app_services.urls', namespace='services')),
    path('about/', include('app_about.urls', namespace='about')),
    path('user/', include('app_user.urls', namespace='user')),
    path('mediafiles/', include('app_mediafiles.urls', namespace='app_mediafiles')),
    path('news/', include('app_news.urls', namespace='news')),
    path('search', include('app_search.urls', namespace='search')),
]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dss/app_objects/models.py
from django.db import models
from django.urls import reverse
# from common.utils import translite
from django.utils.safestring import mark_safe
from ckeditor_uploader.fields import RichTextUploadingField
from app_mediafiles.models import Icon, Image
import random
# from app_services.models import TypeService
# from app_contacts.models import Contact
import logging
logger = logging.getLogger(__name__)
# from app_services.models import TypeService


class Object(models.Model):
    '''\
        Информация о объектах
        название, адрес, геометка.
        Выводиться в меню как название и иконка, ранжируется по важности
    '''
    class Meta:
        verbose_name = 'Объект'
        verbose_name_plural = 'Объекты'

    MAX_SHORT_NAME = 20
    MAX_LONG_NAME = 250

    short_name = models.CharField(
        'краткое имя',
        max_length=MAX_SHORT_NAME,
        help_text=f'Короткое имя объекта (не более {MAX_SHORT_NAME} символов)'
    )
    name = models.CharField(
        'официальное имя',
        max_length=MAX_LONG_NAME,
        help_text=f'Полное официальное имя (не более {MAX_LONG_NAME}  символов)'
    )
    slug = models.SlugField(
        'slug имя в url',
        unique=True,
        db_index=True,
        max_length=MAX_SHORT_NAME,
        help_text='только латинские буквы и цифры'
    )
    address = models.CharField(
        'адрес',
        max_length=200,
        help_text='Адрес по форме город, улица, дом'
    )
    description = RichTextUploadingField(
        'краткое описание',
        max_length=3000,
        blank=True,
        null=True
    )
    icon_lib = models.ForeignKey(
        Icon,
        verbose_name='иконка',
        on_delete=models.PROTECT,
        default=14
    )
    order = models.SmallIntegerField(
        'Сортировка',
        default=100,
    )
    start_date = models.DateField(
        'дата ввода в эксплуатацию',
        null=True,
        blank=True
    )
    square = models.CharField(
        'площадь',
        max_length=11,
        default='-'
    )
    call_center = models.CharField(
        'номер телефона',
        max_length=20,
        default='+7(3012)')
    is_header = models.BooleanField(
        'головная организация',
        default=False
    )

    def __str__(self):
        return f'{self.short_name} ({self.name})'

    def get_icon_url(self):
        if self.icon_lib:
            return self.icon_lib.get_icon_url()

    def icon_html_img(self):
        return mark_safe(
            f'<img src="{self.get_icon_url()}" width="50" height="50" />')
    icon_html_img.short_description = 'Иконка'

    def get_areas(self):
        return self.sportarea.all()

    def get_absolute_url(self):
        return reverse('objects:detail_obj', kwargs={"slug": self.slug})

    def get_random_photo(self):
        photos = []
        obj_galery = ObjectGallery.objects.get(obj=self)
        for photo in obj_galery.photos.all():
            photos.append(
                {'url': photo.get_url_middle_img(),
                 'alt': photo.alt_txt}
            )
        if photos:
            return random.choice(photos)

    def get_num_areas(self):
        return self.sportarea.all().count()
    get_num_areas.short_description = 'спортплощадок'

    def get_num_vacancy(self):
        return '0'
    
    def get_phones(self):
        phones = []
        for area in self.get_areas():
            for phone in area.get_phones():
                phones.append(phone)
        return phones

class SportArea(models.Model):
    '''\
        Спортивная площадка на объекте'''
    class Meta:
        verbose_name = 'спортплощадка'
        verbose_name_plural = 'спортплощадки'

    name = models.CharField(
        'название',
        max_length=35,
        help_text='бассейн, стадион, тренажерный зал, универсальный зал и пр.'
    )
    slug = models.SlugField(
        'slug имя в url',
        unique=True,
        db_index=True,
        max_length=25,
        help_text='желательно английское название'
    )
    icon = models.ForeignKey(
        Icon,
        verbose_name='файл иконки',
        on_delete=models.PROTECT
    )
    order = models.IntegerField(
        'сортировка',
        default=100
    )
    description = RichTextUploadingField(
        'краткое описание',
        max_length=1500,
        default='',
        help_text='описание спортплощадки без характеристик и расписания'
    )
    obj = models.ForeignKey(
        Object,
        verbose_name='Объект',
        on_delete=models.PROTECT,
        related_name='sportarea',
        blank=True,
        null=True
    )
    inviting_mes = models.CharField(
        'слоган или призыв к посещению',
        max_length=90,
        default='призывной призыв или слоган'
    )
    characteristics = models.JSONField(
        'характеристики спортплощадки',
        blank=True,
        null=True
    )

    def __str__(self):
        short_name_obj = self.obj.short_name if self.obj else '-'
        return f'{self.name} ({short_name_obj})'

    def get_icon_url(self):
        if not self.icon:
            return '/media/emptyicon.png'
        return self.icon.get_icon_url()

    def icon_html_img(self):
        return mark_safe(
            f'<img src="{self.get_icon_url()}" width="50" height="50" />')
    icon_html_img.short_description = 'Иконка'
    
    def get_random_photo(self):
        photos = []
        area_galery = SportAreaGallery.objects.get(sportarea=self)
        for photo in area_galery.photos.all():
            photos.append(
                {'url': photo.get_url_middle_img(),
                 'alt': photo.alt_txt}
            )
        if photos:
            return random.choice(photos)
    
    def get_phones(self):
        if hasattr(self, 'contact_area'):
            return self.contact_area.phone_set.all()
        else:
            logger.warning(f"{self} не имеет контактов")
            return []
        
    def get_services(self):
        return self.service_set.all()
        
    def get_typeservices(self):
        services = self.get_services()
        typeservices = set([item.typeservice for item in services])
        return set(typeservices)
    
    def get_separate_services(self):
        typeservices = self.get_typeservices()
        all_services = self.get_services()
        result = {}
        for typeservice in typeservices:
            result[typeservice.get_category_display()] = all_services.filter(typeservice=typeservice)
        return result

class ObjectGallery(models.Model):
    '''\
        Галерея фотографий объектов'''
    class Meta:
        verbose_name = 'фотография объекта'
        verbose_name_plural = 'фотографии объектов'

    obj = models.ForeignKey(
        Object,
        verbose_name='Объект',
        on_delete=models.PROTECT,
        related_name='gallery',
        unique=True
    )
    photos = models.ManyToManyField(
        Image,
        verbose_name='фотографии',
    )

    def __str__(self):
        return f'фото {self.obj.short_name}'
    
    def get_count_photos(self):
        return self.photos.all().count()
    get_count_photos.short_description = 'фотографий'

    def get_short_name(self):
        return self.obj.short_name
    get_short_name.short_description = 'имя'


class SportAreaGallery(models.Model):
    '''\
        Галерея фотографий спортплощадок'''
    class Meta:
        verbose_name = 'фотография спортплощадки'
        verbose_name_plural = 'фотографии спортплощадок'

    sportarea = models.ForeignKey(
        SportArea,
        verbose_name='спортплощадка',
        unique=True,
        on_delete=models.PROTECT
    )
    photos = models.ManyToManyField(
        Image,
        verbose_name='фотографии',
    )

    def __str__(self):
        area_name = self.sportarea.name
        obj_name = self.sportarea.obj.short_name
        return f'{area_name} ({obj_name})'
    
    def get_count_photos(self):
        return self.photos.all().count()
    get_count_photos.short_description = 'фотографий'

    def get_object(self):
        return self.sportarea.obj
    get_object.short_description = 'объект'

    

dss/app_objects/views.py
from django.views.generic.base import TemplateView
from common.mixins import TitleMixin, ObjectsMixin
from .models import Object, ObjectGallery, SportArea
from app_services.models import Service
from django.views.generic.detail import DetailView
from django.views.generic import ListView
from app_news.models import News
from calendar import Calendar
from datetime import datetime, timedelta
from django.shortcuts import get_object_or_404
from app_tags.models import Tag
from django.utils import timezone

def name_of_week(day):
    return ['Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье'][day]

def name_of_month(month):
    return ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 
            'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь'][month-1]

class IndexView(TitleMixin, TemplateView):
    template_name = 'app_objects/index.html'
    title = "ДСС:объекты"
    

class DetailObjectView(TitleMixin, ObjectsMixin, DetailView):
    model = Object
    context_object_name = 'object'
    template_name = 'app_objects/detail.html'
    title = "ДСС: о спортобъекте"
    # objects = Object.objects.all()
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        obj = self.get_object()
        id = obj.pk
        context['object_id'] = id
        # вытащить новости и важные события связанные с конкретным объектом
        # startDate = timezone.now() - timedelta(days=30)
        # endDate = timezone.now() + timedelta(days=30)
        # object_news = []
        # events = []
        # for news in News.objects.filter(date_activation__range=(startDate, endDate)).order_by("-date_activation"):
        #     if news.valid_until_date > timezone.now():
        #         continue
        #     if news.important:
        #         events.append(news)
        #     object_news.append(news)
        tags = Tag.objects.filter(tag__in=[obj.short_name])
        context['events'] = News.objects.get_actual_events(tags=tags)[:3]
        context['objects_news'] = News.objects.get_actual_news(tags=tags)[:6]
        
        # context['services'] = self.object.services.filter(object=self.object.pk).order_by('order')
        return context

class ListObjectsView(TitleMixin, ListView):
    model = Object
    context_object_name = 'objects'
    template_name = 'app_objects/index.html'
    ordering = ['-order']
    title = "ДСС: список объектов"
    
    def get_queryset(self):
        objects = Object.objects.all().order_by('-order')
        return objects
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        objects_news = News.objects.filter(tags__in=[2])
        context['objects_news'] = objects_news[:3]
        return context
    
class DetailAreaView(TitleMixin, DetailView):
    model = SportArea
    context_object_name = 'area'
    template_name = 'app_objects/area.html'
    title = "ДСС: спортплощадка"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        obj_slug = self.kwargs.get('obj_slug')
        object = get_object_or_404(Object, slug=obj_slug)
        context['object'] = object
        tags = Tag.objects.filter(tag__in=[object.short_name, 'новость'])
        startDate = timezone.now() - timedelta(days=30)
        endDate = timezone.now() + timedelta(days=30)
        object_news = []
        events = []
        for news in News.objects.filter(date_activation__range=(startDate, endDate)).order_by("-date_activation"):
            if news.valid_until_date > timezone.now():
                continue
            if news.important:
                events.append(news)
            object_news.append(news)
        context['objects_news'] = object_news[:6]
        context['events'] = events[:3]
        return context

dss/app_objects/templates/app_objects/index.html
{% extends 'home/base_dep.html' %}

{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'home/css/2lv.css' %}">
{% endblock %}

{% block content %}
<main class="main">
  <div class="wrapper">
      <div class="head">
          <div class="head__column">
              <h1 class="head__title">Спортивные объекты</h1>
              <ul class="bradcrumbs"  itemscope itemtype="https://schema.org/BreadcrumbList">
                  <li class="bradcrumbs__item" itemprop='itemListElement' itemscope itemtype='https://schema.org/ListItem'>
                      <a href="/" class="bradcrumbs__link" itemprop="item">Главная</a>
                  </li>
                  <li class="bradcrumbs__item">
                    <a href="#" itemprop="item" disabled>Спортивные объекты</a>
                  </li>
              </ul>
          </div>
          <div class="head__search">
              <form class="search" action="search.html" method="get">
                  <input type="search" value=""  class="search__input">
                  <button type="submit" class="search__button">
                      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16" fill="none">
                          <path d="M15.875 13.4423L12.3417 9.8641C12.9167 8.86019 13.2167 7.74382 13.2167 6.61911C13.2167 2.97006 10.25 0 6.60833 0C2.96667 0 0 2.97006 0 6.61911C0 10.2682 2.96667 13.2382 6.60833 13.2382C7.77083 13.2382 8.92083 12.9175 9.94583 12.3051L13.4625 15.8709C13.5417 15.95 13.6542 16 13.7667 16C13.8792 16 13.9917 15.9542 14.0708 15.8709L15.875 14.0463C16.0417 13.8756 16.0417 13.609 15.875 13.4423ZM6.60833 2.5785C8.83333 2.5785 10.6417 4.39052 10.6417 6.61911C10.6417 8.8477 8.83333 10.6597 6.60833 10.6597C4.38333 10.6597 2.575 8.8477 2.575 6.61911C2.575 4.39052 4.38333 2.5785 6.60833 2.5785Z" fill="#A8A8A8" fill-opacity="0.3"/>
                        </svg>
                  </button>
              </form>
          </div>
      </div>
  </div>
  <section class="wrapper">
      <div class="important-news">
          {% for news in objects_news %}
          <div class="important-news__card important-news__card-danger">
              <h3 class="important-news__title">
                  <a href="{% url 'news:detail' news.slug %}">{{news.title}}</a>
              </h3>
              <p class="important-news__text">{{news.exerpt}}</p>
          </div>
          {% endfor %}
      </div>
  </section>
  <section class="wrapper">
      <div class="cards">
          {% for object in objects %}
          <div class="card" >
              <div class="card__top">
                  <img class="card__img" src="{{object.get_random_photo.url}}" alt="{{object.get_random_photo.alt}}">
                  <!-- тут блоки с абсолютным позиционированием TODO -->
                  <ul class="card__label">
                      <li class="phone-btn">
                        <span class="phone-btn__name">колл-центр</span>
                        <a class="phone-btn__phone" href="tel:{{object.call_center}}">{{object.call_center}}</a>
                      </li>
                      {%for phone in object.get_phones|slice:":2" %}
                      <li class="phone-btn">
                        <span class="phone-btn__name">{{phone.name}}</span>
                        <a class="phone-btn__phone" href="tel:{{phone.url}}">{{phone.phone}}</a>
                      </li>
                      {% endfor %}
                  </ul>
              </div>
              <div class="card__text">
                  <h2 class="card__title">
                    <a href="{% url 'objects:detail' object.slug %}">{{ object.name }}</a>
                  </h2>
                  <div class="card__descript">{{ object.description|safe|truncatechars:260}}</div>
              </div>
          </div>
          {% endfor %}
      </div>
  </section>
</main>
{% endblock %}