dss/app_mediafiles/urls.py
from .views import (ImageGalleryView,
                    ImageDetailView, 
                    ImageEditForm,
                    ImageDeleteForm
)
from django.urls import path

app_name = 'app_mediafiles'
urlpatterns = [
    path('', ImageGalleryView.as_view(), name='list'),
    path('<slug:slug>/', ImageDetailView.as_view(), name='detailimg'),
    path('<slug:slug>/edit/', ImageEditForm.as_view(), name='img_edit'),
    path('<slug:slug>/del/', ImageDeleteForm.as_view(), name='img_del')
]

dss/dss/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('home.urls', namespace='home')),
    path('lk/', include('app_lk.urls', namespace='lk')),
    path('objects/', include('app_objects.urls', namespace='objects')),
    path('services/', include('app_services.urls', namespace='services')),
    path('about/', include('app_about.urls', namespace='about')),
    path('user/', include('app_user.urls', namespace='user')),
    path('mediafiles/', include('app_mediafiles.urls', namespace='app_mediafiles')),
    path('news/', include('app_news.urls', namespace='news')),
    path('search', include('app_search.urls', namespace='search')),
]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dss/home/urls.py
from django.urls import path
from .views import IndexView

app_name = 'home'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    
]

dss/app_mediafiles/models.py
from django.db import models
import uuid
from pathlib import Path
from django.conf import settings
from django.utils.safestring import mark_safe
from PIL import Image as PImage
from django.core.files import File
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.core.files.base import ContentFile
from io import BytesIO
from django.urls import reverse
from .templatetags.fsize_tag import filesize
from django.utils.safestring import mark_safe
import os
from app_tags.models import Tag
from django.utils import timezone


# папки для иконок и фотографий
IMAGE_FOLDER_ICON = 'imagelibrary/icon'
IMAGE_FOLDER_PHOTO = 'imagelibrary/photo'
# подпапки миниатюр
MIDDLE = 'middle'
SMALL = 'thumbnail'
LARGE = 'large'
# размеры миниатюр
WIDTH_THUMBNAIL = 150
WIDTH_MEDIUM = 320
WIDTH_LARGE = 1080
# максимальная длинна файла
MAX_LEN_FILENAME = 70
# поля для миниатюр в экземпляре фотографии
MAX_TITLE = 90
MAX_CAPTION = 260
miniature = {
    'large': WIDTH_LARGE,
    'medium': WIDTH_MEDIUM,
    'thumbnail': WIDTH_THUMBNAIL
}


def path_icon_file(instance, filename):
    extentions = Path(filename).suffix[1:]
    filename = f"{uuid.uuid4()}.{extentions}"
    path = Path(IMAGE_FOLDER_ICON, filename)
    return path


def path_photo_file(instance, filename):
    extentions = Path(filename).suffix[1:]
    filename = f"{uuid.uuid4()}.{extentions}"
    path = Path(IMAGE_FOLDER_PHOTO, filename)
    return path


def filename_photo_file(instance, filename):
    extentions = Path(filename).suffix[1:]
    filename = Path(filename).stem
    if len(filename) > MAX_LEN_FILENAME:
        filename = filename[:MAX_LEN_FILENAME]
    path = Path(IMAGE_FOLDER_PHOTO, f"{filename}.{extentions}")
    return path


class Icon(models.Model):
    """
    Иконка и связанная с иконкой текстовая информация
    """
    class Meta:
        verbose_name = 'Иконка'
        verbose_name_plural = 'Иконки'
    name = models.CharField(max_length=60,
                            default='иконка ...',
                            help_text='иконка бассейна, иконка стадиона и пр.')
    image = models.ImageField(upload_to=path_icon_file)
    created = models.DateTimeField('дата создания', auto_now_add=True)
    width = models.IntegerField('ширина', blank=True, null=True)
    height = models.IntegerField('высота', blank=True, null=True)

    def save(self, *args, **kwargs):
        """После сохранения получить размеры иконки. Так не надо делать.
        Альтернатива - сигналы pre_save и post_save"""
        super(Icon, self).save(*args, **kwargs)
        # image = PImage.open(car.photo)
        im = PImage.open(Path(settings.MEDIA_ROOT, self.image.name))
        self.width, self.height = im.size
        super(Icon, self).save(*args, **kwargs)

    def get_icon_url(self):
        if not self.image:
            return '/media/emptyicon.png'
        return self.image.url

    def icon_html_img(self):
        return mark_safe(f'<img src="{self.get_icon_url()}" alt="{self.name}" style="width:80px">')
    icon_html_img.short_description = 'Иконка'

    def __str__(self):
        return f'{self.name} (иконка)'

    def img_size(self):
        """Image size."""
        return "%s x %s" % (self.width, self.height)
    img_size.short_description = 'размер'


# class Tag(models.Model):
#     class Meta:
#         verbose_name = 'Метка'
#         verbose_name_plural = 'Метки'
#     tag = models.CharField(max_length=50)
#     def __str__(self):
#         return self.tag


class Image(models.Model):
    '''\
        Медиабиблиотека изображений, где каждый элемент имеет описание, имя, размер оригинала и миниатюры'''
    class Meta:
        verbose_name = 'Изобажение'
        verbose_name_plural = 'Галерея изображений'
    title = models.CharField('заголовок', max_length=MAX_TITLE)
    caption = models.TextField('подпись-описание', max_length=MAX_CAPTION)
    slug = models.SlugField(
        'часть url',
        max_length=MAX_TITLE,
        db_index=True,
        unique=True
    )
    alt_txt = models.CharField(
        'альтернативная подпись',
        max_length=MAX_TITLE,
        default='fill necessarily! ')
    date_public = models.DateTimeField(
        'дата загрузки',
        default=timezone.now)
    img_file_size = models.IntegerField(
        'объем файла',
        blank=True,
        null=True)
    img_mode = models.CharField(
        max_length=10,
        blank=True,
        null=True)
    width = models.IntegerField('ширина', blank=True, null=True)
    height = models.IntegerField('высота', blank=True, null=True)
    media_type = models.CharField(
        'расширение',
        max_length=5,
        help_text='расширение файла',
        blank=True,
        null=True)
    image = models.ImageField('файл картинки', upload_to=path_photo_file)
    thumbnail = models.ImageField(
        'миниатюра самая маленькая',
        blank=True,
        null=True,
        upload_to=Path(IMAGE_FOLDER_PHOTO, SMALL),)
    medium = models.ImageField(
        'миниатюра средняя',
        blank=True,
        null=True,
        upload_to=Path(IMAGE_FOLDER_PHOTO, MIDDLE))
    large = models.ImageField(
        'миниатюра большая',
        blank=True,
        null=True,
        upload_to=Path(IMAGE_FOLDER_PHOTO, LARGE))
    tags = models.ManyToManyField(Tag, blank=True)

    # def get_path_forigin(self):
    #     return self.image.name

    # def get_path_fmedium(self):
    #     if self.medium:
    #         return self.medium.name

    # def get_path_fsmall(self):
    #     if self.thumbnail:
    #         return self.thumbnail.name
    def get_news(self):
        news = self.news.all()
        if news:
            news = news.first()
            return news.excerpt
        else:
            return 'с новостью не связан'

    def get_url_middle_img(self):
        if self.thumbnail:
            return self.image.url

    def photo_img(self, max_width=400):
        if not self.image:
            return '/media/emptyhumbnail.png'
        if max_width < WIDTH_THUMBNAIL:
            return mark_safe(f'<a href="{self.image.url}"><img border="0" alt="" src="{self.thumbnail.url}" width="{max_width}" /></a>')
        elif WIDTH_THUMBNAIL <= max_width < WIDTH_MEDIUM:
            return mark_safe(f'<a href="{self.image.url}"><img border="0" alt="" src="{self.medium.url}" width="{max_width}" /></a>')
        else:
            return mark_safe(f'<a href="{self.image.url}"><img border="0" alt="" src="{self.large.url}" width="{max_width}" /></a>')
    photo_img.short_description = 'картинка под размер'

    def thumbnail_html(self):
        if self.thumbnail:
            return mark_safe(f'<a href="{self.image.url}"><img border="0" alt="" src="{self.thumbnail.url}" height="50" /></a>')
        elif self.medium:
            return mark_safe(f'<a href="{self.image.url}"><img border="0" alt="" src="{self.medium.url}" height="50" /></a>')
        else:
            return mark_safe(f'<a href="{self.image.url}"><img border="0" alt="" src="{self.image.url}" height="50" /></a>')
    thumbnail_html.allow_tags = True
    thumbnail_html.short_description = 'миниатюра'

    def __str__(self):
        return f"{self.title} ({self.pk}) ({self.tags_list()})"

    def get_img_size(self):
        return f"{self.width}x{self.height} px"
    get_img_size.short_description = 'размер картинки'

    def get_tags(self):
        return self.tags.all()

    def tags_list(self):
        lst = [x[1] for x in self.tags.values_list()]
        return mark_safe(', '.join(lst))
    tags_list.short_description = 'список тэгов'

    def is_caption(self):
        return bool(self.caption)
    is_caption.boolean = True
    is_caption.short_description = 'есть подпись'

    def get_absolute_url(self):
        return reverse("app_mediafiles:detailimg", kwargs={"slug": self.slug})

    def get_next_slug(self):
        next = Image.objects.filter(pk__gt=self.pk).order_by('pk').first()
        if next:
            return next.slug

    def get_prev_slug(self):
        prev = Image.objects.filter(pk__lt=self.pk).order_by('-pk').first()
        if prev:
            return prev.slug

    def get_fsize(self):
        return filesize(self.img_file_size)
    get_fsize.short_description = 'размер файла'

    def get_large_html(self):
        if os.path.exists(self.large.path):
            img = PImage.open(self.large)
            width, height = img.size
            name = self.large.name
            fimg = BytesIO()
            img.save(fimg, img.format)
            fsize = filesize(len(fimg.getvalue()))
            return mark_safe(f"<a href={self.large.url}>{name} ({width}x{height}) {fsize}</a>")

    def get_medium_html(self):
        if os.path.exists(self.medium.path):
            img = PImage.open(self.medium)
            width, height = img.size
            name = self.medium.name
            fimg = BytesIO()
            img.save(fimg, img.format)
            fsize = filesize(len(fimg.getvalue()))
            return mark_safe(f"<a href={self.medium.url}>{name} ({width}x{height}) {fsize}</a>")

    def get_small_html(self):
        if os.path.exists(self.thumbnail.path):
            img = PImage.open(self.thumbnail)
            width, height = img.size
            name = self.thumbnail.name
            fimg = BytesIO()
            img.save(fimg, img.format)
            fsize = filesize(len(fimg.getvalue()))
            return mark_safe(f"<a href={self.thumbnail.url}>{name} ({width}x{height})  {fsize}</a>")
        
    


@receiver(post_save, sender=Image)
def fill_field_image(sender, instance, created, **kwargs):
    '''после сохранения экземпляра с оригинальной фотографией, узнать его размеры и сгенерировать миниатюры с различными размерами'''
    if created:
        img = PImage.open(instance.image)
        if not instance.width:
            instance.width, instance.height = img.size
        instance.img_mode = img.mode
        img_format = img.format
        if not instance.media_type:

dss/app_mediafiles/forms.py
from django import forms
from .models import Image as ImageMedia

class ImageForm(forms.ModelForm):
    class Meta:
        model = ImageMedia
        fields = ('slug', 'title', 'caption', 'alt_txt')
        

dss/app_mediafiles/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, DeleteView
from .models import Image as ImageMedia
from .forms import ImageForm
from django.views.generic.edit import UpdateView
from django.urls import reverse_lazy, reverse

# Create your views here.


class ImageGalleryView(ListView):
    template_name = 'app_mediafiles/index.html'
    paginate_by = 8
    model = ImageMedia
    context_object_name = 'images'
    ordering = ('pk',)
    title = 'медиабиблиотека'
        
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        curent_page = kwargs.get("page", 1)
        page = context['page_obj']
        context['paginator_range'] = page.paginator.get_elided_page_range(page.number, on_each_side=1, on_ends=1)
        return context
    
class ImageDetailView(DetailView):
    model = ImageMedia
    template_name = 'app_mediafiles/detail_img.html'
    context_object_name = 'image'
    
    
class ImageEditForm(UpdateView):
    model = ImageMedia
    fields = ['slug', 'title', 'caption', 'alt_txt']
    template_name = 'app_mediafiles/edit_img.html'
    context_object_name = 'image'
    
class ImageDeleteForm(DeleteView):
    model = ImageMedia
    template_name = 'app_mediafiles/delete_img.html'
    
    def get_success_url(self) -> str:
        return reverse('app_mediafiles:detailimg', kwargs = {
                     'slug': self.object.get_next_slug()})
    

    

dss/app_mediafiles/templates/app_mediafiles/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gallery</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/fancybox/fancybox.umd.js"></script>
    <link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/fancybox/fancybox.css"
    />
    <style>
        .thumb img {
            -webkit-filter: grayscale(0);
            filter: none;
            border-radius: 5px;
            background-color: #fff;
            border: 1px solid #ddd;
            padding: 5px;
        }

        .thumb img:hover {
            -webkit-filter: grayscale(1);
            filter: grayscale(1);
        }

        .thumb {
            padding: 5px;
        }

        .thumbnail {
            width: 270px;
            height: 250px;
            float:left;
            background: #000;
        }

        .pagination {
            margin-left: auto;
            margin-right: auto;
            width: max-content
        }

    </style>
</head>
<body>
    <h2>Медиабиблиотека</h2>
    <div class="container">
        <div class="row mb-2">
            {% for image in page_obj.object_list %}
            <div class="col-lg-3 col-md-4 col-6 thumb">
                <div class="thumbnail">
                    <a href="{% url 'app_mediafiles:detailimg' image.slug %}" data-fancybox="gallery" data-caption="{{image.caption}}_{{forloop.counter}}">
                        <img width="150" height="150" src="{{image.image.url}}" class="attachment-medium size-medium" alt="{{image.image.alt_txt}}" decoding="async" loading="lazy" srcset="{{image.medium.url}} 300w, {{image.thimbnail.url}} 150w, {{image.large.url}} 800w" sizes="(max-width: 300px) 100vw, 300px" style="width:100%;height:100%;max-width:604px;" />
                    </a>
                </div>
            </div>
            {% endfor %}
        </div>
        <ul class="pagination">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Предыдущий</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#">Предыдущий</a>
            </li>
            {%endif%}

            {% for page_number in paginator_range %}
            {% if page_number == page_obj.paginator.ELLIPSIS %}
            <li class="page-item">
                {{page_number}}
            </li>
            {% else %}
            <li class="page-item {% if page_number == page_obj.number %}active{% endif %}">
                <a class="page-link" href="?page={{ page_number }}">{{page_number}}
                </a>
            </li>
            {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">Следующий</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link disabled" href="#">Следующий</a>
            </li>
            {% endif %}
          </ul>
        {% comment %} {% include  'app_news/paginator_block.html' %} {% endcomment %}
    </div>
    
    {% comment %} <h3>{{image.title}}
    <p class="attachment">
        <a href="{{image.image.url}}">
            <img width="300" height="300" src="{{image.image.url}}" class="attachment-medium size-medium" alt="{{image.image.alt_txt}}" decoding="async" loading="lazy" srcset="https://admin.dss-sport.ru/wp-content/uploads/2023/05/pgcsyg4xxgk-300x300.jpg 300w, https://admin.dss-sport.ru/wp-content/uploads/2023/05/pgcsyg4xxgk-150x150.jpg 150w, https://admin.dss-sport.ru/wp-content/uploads/2023/05/pgcsyg4xxgk.jpg 604w" sizes="(max-width: 300px) 100vw, 300px" style="width:100%;height:100%;max-width:604px;" />
        </a>
    </p>
    <p>{{image.caption}}</p>
    <p>{{image.description}}</p>
    {% endfor %} {% endcomment %}
</body>
</html>

dss/app_mediafiles/templates/app_mediafiles/detail_img.html
{% extends 'home/base_dep.html' %}

{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'home/css/2lv.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/fancybox/fancybox.umd.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/fancybox/fancybox.css"/>
    

    <script src="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/fancybox/fancybox.umd.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/fancybox/fancybox.css"/>

    <style>
        .thumb {
            height: 65vh;
        }
        .img_window {
            display: block;
            margin-left: auto;
            margin-right: auto;
            width: 100%
        }
        .nav_btn {
            display: flex;
            align-items: center;
            background: #ccc;
            justify-content: center;
        }
    </style>
    <link rel="stylesheet" href="{% static 'home/css/media.css' %}">
{% endblock %}

{% load fsize_tag %}


{% block content %}
<div class="container-fluid">
    <div class="row">
        {% if image.get_prev_slug %}
        <a class="col-1 nav_btn" href="{% url 'app_mediafiles:detailimg' image.get_prev_slug %}">
            &#10092;
        </a>
        {% else %}
        <div class="col-1 nav_btn">
            &#215;
        </div>
        {% endif%}
        <div class="col-10">
            <h2 class="text-center">
                {% if image.title %}
                    {{image.title}}
                {% else %}
                    нет заголовка
                {% endif %}
            </h2>
            <p class="text-center">
                {% if image.caption %}
                    {{image.caption}}
                {% else %}
                    нет подписи
                {% endif %}
            </p>
            <p class="text-center">
                {% if image.alt_txt %}
                    {{image.alt_txt}}
                {% else %}
                    нет альтернативной подписи
                {% endif %}
            </p>
            {% if user.is_staff %}
            <div class="btn-group">
                <a href="{% url 'app_mediafiles:img_edit' image.slug %}" class="btn btn-primary">
                    редактировать
                </a>
                <a href="{% url 'app_mediafiles:img_del' image.slug %}" class="btn btn-danger">
                    удалить
                </a>
            </div>
            {% endif %}
            <div class="thumb mb-2">
                <a href="{{image.image.url}}">
                    <img width="800" src="{{image.image.url}}" class="img_window" alt="{{image.alt_txt}}" decoding="async" loading="lazy" srcset="{{image.medium.url}} 200w, {{image.thumbnail.url}} 150w, {{image.large.url}} 304w" sizes="(max-width: 300px) 100vw, 300px" style="width:100%;height:100%;max-width:604px;" />
                </a>
            </div>
            <p>Параметры картинки: 
                <span>{{image.get_img_size}}</span>,
                <span>{{image.img_mode}}</span>,
                <span>{{image.media_type}}</span>,
                <span>{{image.mime_type}}</span>
            </p>
            <p>Параметры файла:
                <span>{{image.img_file_size|filesize}}</span>,
                <span>{{image.image.name}}</span>,
                время создания: <span> {{image.date_public|date:'d.m.Y'}} {{image.date_public|time:'H:i'}}</span>
            </p>
        </div>
        {% if image.get_next_slug %}
        <a class="col-1 nav_btn" href="{% url 'app_mediafiles:detailimg' image.get_next_slug %}">
            &#10093;
        </a>
        {% else %}
        <div class="col-1 nav_btn">
            &#215;
        </div>
        {% endif%}
    </div>
    
</div>
{% endblock %}

{% block bradcrumbs %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb" itemscope itemtype="https://schema.org/BreadcrumbList">
    <li class="breadcrumb-item" itemprop='itemListElement' itemscope itemtype='https://schema.org/ListItem'>
      <a href="{% url 'home:index' %}" itemprop="item">
        <span itemprop="name">Главная</span>
      </a>
    </li>
    <li class="breadcrumb-item" itemprop='itemListElement' itemscope itemtype='https://schema.org/ListItem'>
      <a href="{% url 'app_mediafiles:list'%}" itemprop="item">
        <span itemprop="name">Медиабиблиотека</span>
      </a>
    </li>
  </ol>
</nav>
{% endblock %}

dss/app_mediafiles/templates/app_mediafiles/index.html
{% extends 'home/base_dep.html' %}

{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'home/css/2lv.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/fancybox/fancybox.umd.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/fancybox/fancybox.css"/>
    <style>
        .thumb img {
            -webkit-filter: grayscale(0);
            filter: none;
            border-radius: 5px;
            background-color: #fff;
            border: 1px solid #ddd;
            padding: 5px;
        }

        .thumb img:hover {
            -webkit-filter: grayscale(1);
            filter: grayscale(1);
        }

        .thumb {
            padding: 5px;
        }

        .thumbnail {
            width: 270px;
            height: 250px;
            float:left;
            background: #000;
        }

        .pagination {
            margin-left: auto;
            margin-right: auto;
            width: max-content
        }

    </style>
    <link rel="stylesheet" href="{% static 'home/css/media.css' %}">
{% endblock %}

{% block content %}
    <div class="d-flex justify-content-between">
    <h2>Медиабиблиотека</h2>
    {% comment %} {% if obj_filter|length == 1 %}
        {% for item in obj_filter %}
        <div class="form-check form-check-inline">
          <input class="form-check-input" disabled checked type="checkbox" id="check{{loop.counter}}" value="{{item.slug}}" name="object">
          <label class="form-check-label" for="check{{loop.counter}}">{{item.short_name}}</label>
        </div>
        {%endfor%}
      {%else%}
        {% for item in obj_filter %}
        <div class="form-check form-check-inline">
          <input class="form-check-input" 
          {% if item.slug in param_objs %}
            checked
            {% else%}
            unchecked
          {%endif%}
           type="checkbox" id="check{{loop.counter}}" value="{{item.slug}}" name="object">
          <label class="form-check-label" for="check{{loop.counter}}">{{item.short_name}}</label>
        </div>
        {%endfor%}
      {%endif%} {% endcomment %}
      <div class="form-check form-check-inline">
        <input class="form-check-input" disabled checked type="checkbox" id="check{{loop.counter}}" value="{{item.slug}}" name="object">
        <label class="form-check-label" for="check{{loop.counter}}">acr</label>
      </div>
    </div>
    <div class="container">
        <div class="row mb-2">
            {% for image in page_obj.object_list %}
            <div class="col-lg-3 col-md-4 col-6 thumb">
                <div class="thumbnail">
                    <a href="{% url 'app_mediafiles:detailimg' image.slug %}" data-fancybox="gallery" data-caption="{{image.caption}}_{{forloop.counter}}">
                        <img width="150" height="150" src="{{image.image.url}}" class="attachment-medium size-medium" alt="{{image.image.alt_txt}}" decoding="async" loading="lazy" srcset="{{image.medium.url}} 300w, {{image.thimbnail.url}} 150w, {{image.large.url}} 800w" sizes="(max-width: 300px) 100vw, 300px" style="width:100%;height:100%;max-width:604px;" />
                    </a>
                </div>
            </div>
            {% endfor %}
        </div>
        <ul class="pagination">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Предыдущий</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#">Предыдущий</a>
            </li>
            {%endif%}

            {% for page_number in paginator_range %}
            {% if page_number == page_obj.paginator.ELLIPSIS %}
            <li class="page-item">
                {{page_number}}
            </li>
            {% else %}
            <li class="page-item {% if page_number == page_obj.number %}active{% endif %}">
                <a class="page-link" href="?page={{ page_number }}">{{page_number}}
                </a>
            </li>
            {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">Следующий</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link disabled" href="#">Следующий</a>
            </li>
            {% endif %}
          </ul>
        {% comment %} {% include  'app_news/paginator_block.html' %} {% endcomment %}
    </div>
 {% endblock %}

 {% block bradcrumbs %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb" itemscope itemtype="https://schema.org/BreadcrumbList">
    <li class="breadcrumb-item" itemprop='itemListElement' itemscope itemtype='https://schema.org/ListItem'>
      <a href="{% url 'home:index' %}" itemprop="item">
        <span itemprop="name">Главная</span>
      </a>
    </li>
    <li class="breadcrumb-item" itemprop='itemListElement' itemscope itemtype='https://schema.org/ListItem'>
      <a href="{% url 'app_mediafiles:list'%}" itemprop="item">
        <span itemprop="name">Медиабиблиотека</span>
      </a>
    </li>
  </ol>
</nav>
{% endblock %}